// Auth
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';

// Trips
export const TRIP_CREATED = 'TRIP_CREATED';
export const TRIP_CREATE_ERROR = 'TRIP_CREATE_ERROR';
export const TRIP_SET_MEMBER_ERROR = 'TRIP_SET_MEMBER_ERROR';
export const TRIP_SETTLE_ERROR = 'TRIP_SETTLE_ERROR';

// Transactions
export const TRANSACTION_CREATE_ERROR = 'TRANSACTION_CREATE_ERROR';
export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';
export const TRANSACTION_EDIT_SUCCESS = 'TRANSACTION_EDIT_SUCCESS';
export const TRANSACTION_EDIT_ERROR = 'TRANSACTION_EDIT_ERROR';
export const TRANSACTION_DELETE_SUCCESS = 'TRANSACTION_DELETE_SUCCESS';
export const TRANSACTION_DELETE_ERROR = 'TRANSACTION_DELETE_ERROR';
